splunk/vscode-extension-splunk

out/customCommand.js
out/customRESTHandler.js
out/modViz.js
package-lock.json

Addresses issue #36 by using the the `fsPath` property of the [URI](https://code.visualstudio.com/api/references/vscode-api#Uri).

Update path handling for creating custom components. #36

---

package.json

Creating this PR not to forget to change path to the schema file because of separating UI part from https://github.com/splunk/addonfactory-ucc-generator repository.
The current migration can be tracked here: https://github.com/splunk/addonfactory-ucc-generator/tree/ucc_ui_lib_migration.

feat: update path to JSON schema for globalConfig validation

---

out/commands/reload.js
out/extension.js
package.json

This PR adds a new command to the extension. It can be accessed from the command palette as 
> **Splunk: Trigger Full Debug Refresh**
The command will reload all reloadable splunkd EAI handlers, similar to the `debug/refresh` endpoint on Search Heads.
This is a common operation during development to ensure all `.conf` files are in effect.
Note that since the `debug/refresh` endpoint is only accessible on `:8000` and can't be authenticated against with a JWT, the command re-implements what the endpoint does under the covers.
First, it identifies all reloadable handlers and subsequently issues parallel POST requests to the respective endpoint. At the end, there will be a log to the Splunk Output Channel imitating, again, what `debug/refresh` returns. …

feat: add new command to mimic debug refresh on SH

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
package-lock.json
package.json
tsconfig.base.json
tsconfig.json
webpack.config.js

This PR moves the build / development process to support Typescript files. 
For now, all JS will work as-is since all valid JavaScript is also valid TypeScript, enabling an incremental adoption of Typescript. But since we need to compile TS sources into JS at build time, webpack is introduced.
Currently, the `main` entrypoint to the extension is `out/extension.js`. With webpack added, the `npm run watch` task will use webpack to compile all sources inside `out/` into the `dist/` folder. Now, `dist/extension.ts` is the new entrypoint for the extension.
The PR changes the "Run Extension" debug task to automatically launch the `npm run watch` task to ensure that webpack is run continuously throughout the development. 
It also adds a new debug task to run the extension in an isolated …

Move extension to webpack-based build to support Typescript sources

---

.babelrc
out/extension.js
out/notebooks/commands.ts
out/notebooks/controller.ts
out/notebooks/provider.ts
out/notebooks/renderer/.eslintrc.json
out/notebooks/renderer/components.jsx
out/notebooks/renderer/visualization.jsx
out/notebooks/serializers.ts
out/notebooks/splunk.ts
out/notebooks/utils.ts
out/notebooks/visualizations.ts
package-lock.json
package.json
spl-language-configuration.json
webpack.config.js

This MR adds initial support for SPL Notes. 
SPL Notes are built based on the [VS Code Notebook Support](https://code.visualstudio.com/blogs/2021/11/08/custom-notebooks) as well as [Splunk UI](https://splunkui.splunk.com/Packages/react-ui/).
Create a new file with `.splnb` extension to create a new SPL Note. There is currently no other way to navigate into an SPL Note, we may add a short command at a later time for that.

Adds SPL Notes functionality

---

out/extension.js
out/notebooks/commands.ts
out/notebooks/controller.ts
out/notebooks/provider.ts
out/notebooks/spl2/controller.ts
out/notebooks/splunk.ts
out/notebooks/utils.ts
package.json
spl2-language-configuration.json
syntaxes/spl2.tmGrammar.json

Building off the existing SPL Notes feature, provide new functionality to execute SPL2 as search jobs (for Splunk deployments supporting the `/services/search/spl2-module-dispatch` endpoint), and view results.
To try this out:
* Configure the following two [Extension Settings](https://github.com/splunk/vscode-extension-splunk/wiki/Extension-Settings) to point to a Splunk deployment which supports `/services/search/spl2-module-dispatch`:
* `Splunk Rest Url`
* `Token` 
* Open any file with the `.spl2nb` extension or files named `modules.json`.
I also drafted this Wiki page to add once this work merges: https://github.com/fantavlik/vscode-extension-splunk/wiki/Splunk-Notebooks

Add ability to dispatch SPL2 via SPL2 Notebooks

---

out/extension.js
out/notebooks/spl2/initializer.ts
out/notebooks/spl2/installer.ts
package-lock.json
package.json

This PR provides functionality when a user opens a SPL2 specific file (currently `.spl2nb` or `modules.json`) to detect and install any missing SPL2 required resources and acceptance of terms including: 
- Detecting whether JAVA is already installed and available in $JAVA_HOME
- If yes, detecting via `java -version` whether Java 17 or later
- If Java 17 or later is detected then record that configuration
- Detect if SPL2 language server has already been installed
- If SPL2 language server hasn't been installed then...
- Provide a dialog indicating that downloading/using the SPL2 Language Server is subject to the Splunk General Terms with options to:
- Accept terms and continue with install (and record that user has accepted terms)
- View Splunk General Terms in browser
- Decline install …

SPL2 installation

---

out/extension.js
out/notebooks/controller.ts
out/notebooks/renderer/components.jsx
out/notebooks/renderer/visualization.jsx
out/notebooks/spl2/initializer.ts
out/notebooks/spl2/installer.ts
package-lock.json
package.json

This PR unlocks the following features:
- Initialize a single SPL2 Language Server (java process spawned by the extension) and client
- Provide language server features such as autocomplete, hover documentation, syntax errors, etc
- Use a single language server for multiple documents, this requires a slight trick to keep the language server up-to-date after switching documents which we do by providing a no-op edit to the open file (replace the first character with itself when switching between documents)
- Provide support for automatically recovering when connection lost to server
- New command to allow the user to forcibly restart the language server if issues are encountered
To see the changes just for the intialization work (there's a separate PR …

Spl2 - Language Server Support

---

out/extension.js
out/notebooks/commands.ts
out/notebooks/controller.ts
out/notebooks/provider.ts
out/notebooks/serializers.ts
out/notebooks/spl2/controller.ts
out/notebooks/spl2/initializer.ts
out/notebooks/spl2/installer.ts
out/notebooks/spl2/serializer.ts
out/notebooks/splunk.ts
package.json

- Provide better error handling and configurability for language server download and install by allowing user to specify custom path to LSP file
- Fix issue with progress bars getting stuck
- Allow users to input earliest and latest times
Demo:
- Serialize the format for SPL2 notebooks saved to disk to more closely match modules.json expectations, example:
```json
{
"modules": [
{
"name": "module1",
"namespace": "",
"definition": "$q1 = from _internal where log_level != \"ERROR\"",
"_vscode": {
"metadata": {
"splunk": {
"earliestTime": "-24h",
"latestTime": "now"
}
},
"outputs": []
}
},
{
"name": "module2",
"namespace": "",
"definition": " $q2 = from main",
"_vscode": {
"metadata": {
"splunk": {
"earliestTime": "@d",
"latestTime": "now"
}
},
"outputs": []
}
}
],
"app": "apps.search"
}
```

Spl2 fixes

---

.github/workflows/ci.yaml
out/extension.js
out/notebooks/commands.ts
out/notebooks/controller.ts
out/notebooks/provider.ts
out/notebooks/renderer/components.jsx
out/notebooks/renderer/visualization.jsx
out/notebooks/serializers.ts
out/notebooks/spl2/controller.ts
out/notebooks/spl2/initializer.ts
out/notebooks/spl2/installer.ts
out/notebooks/spl2/serializer.ts
out/notebooks/splunk.ts
out/notebooks/utils.ts
package-lock.json
package.json
spl2-language-configuration.json
syntaxes/spl2.tmGrammar.json

Add support for SPL2 notebooks for customers with access to SPL2 preview deployments.
There is a full wiki page that I've staged to help with setup including some notes for existing SPL Notebooks: https://github.com/fantavlik/vscode-extension-splunk/wiki/Splunk-Notebooks
Features:
* Guided installation of SPL2 Language Server and Java 17+ (if needed). More details: https://github.com/splunk/vscode-extension-splunk/pull/86
* Ability to execute SPL2 notebooks cells via `spl2-module-dispatch` endpoint and view job results. More details: https://github.com/splunk/vscode-extension-splunk/pull/85
* Support for SPL2 Language Server and Client initialization when `.spl2nb` or `modules.json` files are opened which provides syntax highlighting, autocomplete, hover documentation, code suggestions, …

SPL2 Notebooks

---

.github/workflows/ci.yaml
out/notebooks/commands.ts
out/notebooks/provider.ts
out/notebooks/serializers.ts
out/notebooks/spl2/controller.ts
out/notebooks/spl2/serializer.ts
out/notebooks/splunk.ts

Provide functionality to input the module name and namespace for SPL2 notebooks and use that information when dispatching SPL2 (detect app and namespace from `apps.<app>` and subnamespace from `apps.<app>.my.sub.namespace`).
And provide a new button update the module contents on the connected Splunk deployment using a PUT to the `/services/spl2/modules/<namespace>.<moduleName>` endpoint:
Upon success an info message is provided:
Or an error message popup:

Allow updating SPL2 modules

---

out/notebooks/splunk.ts

The code to detect variables in SPL2 code is a bit primitive at the moment and currently will catch commented-out variables. This tweaks the regex to require a variable to occur at the start of the line with just whitespace before it.

Fix problem with variables in comments

---

out/notebooks/spl2/installer.ts

Splunk VSCode extension currently hardcodes the version we use for LSP, and recently the LSP jar was updated to fix various bugs such as with the `iplocation` command requiring the `prefix` argument in embedded SPL1 queries (even though this is actually not necessary). This jar also adds support for single-line comments as well as various other fixes.
These changes are necessary for SPL2's .conf23 workshop.

Upgrading jar used by LSP to 2.0.366

---

out/extension.js
out/notebooks/spl2/installer.ts
out/notebooks/splunk.ts
package.json

Users were encountering errors with `rmdirSync` failing if the directory was not empty. `rmdirSync` is also deprecated, for `rm -rf` functionality we have moved to `rmSync` with `{ recursive: true, force: true }`.
Also added some additional logging to help debug issues that users encounter.

Fix issue with rmdir failing when directory not empty for some users

---

package.json

We deprecated UCC base UI repository and moved schema to the UCC generator repository.

feat: update URL to globalConfig file

---

out/notebooks/splunk.ts

The spl2-module-dispatch URIs are incorrect, and currently only work in the search app context.
I have confirmed the restmap.conf is looking for search/spl2-module-dispatch, but to set the app context the URIs need to change from `/services/<app>/spl2-module-dispatch` to `/servicesNS/-/<app>/search/spl2-module-dispatch`

Fix the spl2-module-dispatch URI to use servicesNS instead of services

---

out/notebooks/splunk.ts

The JavaScript object URL returns an empty port when using 443 for HTTPS and 80 for HTTP, as per https://developer.mozilla.org/en-US/docs/Web/API/URL/port
This means anyone using Splunkd on port 443 (for example through a reverse proxy), will be unable to connect as the extension will default back to 8089.
Fair warning I havent actually tested this fix, but the logic should be sound.

Fix port behavior of URL() in notebooks.

---

out/notebooks/spl2/initializer.ts

This one-line change adds autocompletion and hover-docs support for all *.spl2 files matching the behavior in SPL2 notebooks:

Add support for SPL2 language server for .spl2 files

---

out/extension.js
out/notebooks/spl2/initializer.ts
out/notebooks/spl2/installer.ts
package.json

Previously we were hardcoding which version to use. Users can also opt-out of this automatic update and/or hardcode to a specific version of the SPL2 Language server if they like, new setting:
In order to make it clear to the user which version of the language server is being used (also helpful for debugging issues for customers) the language server version is now displayed along with the current language server status at the bottom of the SPL2 notebook window:
[Functional test logs](https://github.com/splunk/vscode-extension-splunk/actions/runs/8347808857/job/22848297222?pr=115#step:7:58) also confirm the latest version is discovered and used (2.0.402 at the time of this PR) by default:
This PR also addresses an issue some users noticed where their machine-specific installation settings …

SPL2 notebooks download/use the latest SPL2 language server by default

---

out/searchProvider.js

The endpoint `/search/jobs/export` is depricated as of Splunk version 9.0.1. Updated to use v2 of endpoint.
Ref https://docs.splunk.com/Documentation/Splunk/9.2.1/RESTREF/RESTsearch#search.2Fjobs.2Fexport_.28deprecated.29

fix: updated version of search endpoint /search/v2/jobs/export

---

out/notebooks/controller.ts
out/notebooks/spl2/controller.ts
out/notebooks/splunk.ts
package-lock.json
package.json

This avoids any issues with delays associated with sids or other search artifacts being replicated across the cluster. Currently it's possible that a sid created on one search head may not be recognized by another due to delay in artifact replication. This has been tested on a Splunk Cloud cluster of 3 search heads.
Also included: minor refactor of the `splunk.ts` class to adopt Promises used in the Javascript SDK as of version 2.x per https://github.com/splunk/splunk-sdk-javascript?tab=readme-ov-file#migrate-from-callbacksv1x-to-promiseasync-awaitv2x

Pick a single search head when search head cluster is detected

---

CHANGELOG.md
package.json

- Pick a single search head when search head cluster is detected to prevent replication delay issues
- Improve parsing of SPL2 modules for statement names to handle strings, fields, functions, comments
- Bump fast-xml-parser from 4.3.6 to 4.4.1 
- Bump axios from 0.28.0 to 0.30.0
- Bump braces from 3.0.2 to 3.0.3 
- Fix to update GitHub actions as they were failing
- Add support for V2 search endpoints 
- Updated version of search endpoint /search/v2/jobs/export

Prep for v0.3.4 release
